print("DISSECANDO UMA VÁRIAVEL!")
Algo = input("Digite algo")
print("Seu tipo É",type(Algo))
print("Só tem Espaços?",Algo.isspace())
print("É alphabético?",Algo.isalpha())
print("É Numero?",Algo.isnumeric())
print("É Alphanumerico?",Algo.isalnum())
print("Está em  maiúsculo?",Algo.isupper())
print("Está em minúsculo?",Algo.islower())
print("Está capitalizada?",Algo.istitle())